title: Coronavirus Answers
email: damien@talariasoftware.com
description: JSON API for Coronavirus FAQs at https://faq.coronavirus.gov
twitter_username:
github_username:

theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

collections:
  categories:
    output: false
  content:
    output: false

